spring:
  application:
    name: demo2
  profiles:
    active: dev
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
  sleuth:
    sampler:
      percentage: 1
dubbo:
  registry:
    address: nacos://10.11.1.218:8848
  protocol:
    serialization: KryoSerialization2